# Check API is running.
GET http://localhost:3000/ HTTP/1.1

###
# Basic converation to parse.
POST http://localhost:3000/parse_conversation HTTP/1.1
Content-Type: text/plain

Hi I just had a car accident and wanted to report it. OK, I hope you're alright, what happened?

###
# More complex converation to parse.
POST http://localhost:3000/parse_conversation HTTP/1.1
Content-Type: text/plain

< ./transcripts/claim1.raw.txt
